name: rmTestingWorkflow

on:
  push:
    branches: [ "dev" ]

  workflow_dispatch:

jobs:

  runTests:
    
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      - name: install pytest
        run: pip install pytest

      - name: pytest run
        run: pytest

